/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminMessagesRouteImport } from './routes/app/admin/messages'
import { Route as AppAdminExecutionsRouteImport } from './routes/app/admin/executions'
import { Route as ApiTwilioStatusRouteImport } from './routes/api/twilio.status'
import { Route as ApiTwilioInboundRouteImport } from './routes/api/twilio.inbound'
import { Route as ApiReplExecuteRouteImport } from './routes/api/repl.execute'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminMessagesRoute = AppAdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminExecutionsRoute = AppAdminExecutionsRouteImport.update({
  id: '/admin/executions',
  path: '/admin/executions',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiTwilioStatusRoute = ApiTwilioStatusRouteImport.update({
  id: '/api/twilio/status',
  path: '/api/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioInboundRoute = ApiTwilioInboundRouteImport.update({
  id: '/api/twilio/inbound',
  path: '/api/twilio/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReplExecuteRoute = ApiReplExecuteRouteImport.update({
  id: '/api/repl/execute',
  path: '/api/repl/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/repl/execute': typeof ApiReplExecuteRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/app/admin/executions': typeof AppAdminExecutionsRoute
  '/app/admin/messages': typeof AppAdminMessagesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/repl/execute': typeof ApiReplExecuteRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/app/admin/executions': typeof AppAdminExecutionsRoute
  '/app/admin/messages': typeof AppAdminMessagesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/repl/execute': typeof ApiReplExecuteRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/app/admin/executions': typeof AppAdminExecutionsRoute
  '/app/admin/messages': typeof AppAdminMessagesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/api/repl/execute'
    | '/api/twilio/inbound'
    | '/api/twilio/status'
    | '/app/admin/executions'
    | '/app/admin/messages'
    | '/app/admin/users'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/api/repl/execute'
    | '/api/twilio/inbound'
    | '/api/twilio/status'
    | '/app/admin/executions'
    | '/app/admin/messages'
    | '/app/admin/users'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/api/repl/execute'
    | '/api/twilio/inbound'
    | '/api/twilio/status'
    | '/app/admin/executions'
    | '/app/admin/messages'
    | '/app/admin/users'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReplExecuteRoute: typeof ApiReplExecuteRoute
  ApiTwilioInboundRoute: typeof ApiTwilioInboundRoute
  ApiTwilioStatusRoute: typeof ApiTwilioStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/messages': {
      id: '/app/admin/messages'
      path: '/admin/messages'
      fullPath: '/app/admin/messages'
      preLoaderRoute: typeof AppAdminMessagesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/executions': {
      id: '/app/admin/executions'
      path: '/admin/executions'
      fullPath: '/app/admin/executions'
      preLoaderRoute: typeof AppAdminExecutionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/twilio/status': {
      id: '/api/twilio/status'
      path: '/api/twilio/status'
      fullPath: '/api/twilio/status'
      preLoaderRoute: typeof ApiTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/inbound': {
      id: '/api/twilio/inbound'
      path: '/api/twilio/inbound'
      fullPath: '/api/twilio/inbound'
      preLoaderRoute: typeof ApiTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repl/execute': {
      id: '/api/repl/execute'
      path: '/api/repl/execute'
      fullPath: '/api/repl/execute'
      preLoaderRoute: typeof ApiReplExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminExecutionsRoute: typeof AppAdminExecutionsRoute
  AppAdminMessagesRoute: typeof AppAdminMessagesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminExecutionsRoute: AppAdminExecutionsRoute,
  AppAdminMessagesRoute: AppAdminMessagesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReplExecuteRoute: ApiReplExecuteRoute,
  ApiTwilioInboundRoute: ApiTwilioInboundRoute,
  ApiTwilioStatusRoute: ApiTwilioStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
