/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminMessagesRouteImport } from './routes/app/admin/messages'
import { Route as AppAdminExecutionsRouteImport } from './routes/app/admin/executions'
import { Route as ApiSms8InboundRouteImport } from './routes/api/sms8.inbound'
import { Route as ApiReplExecuteRouteImport } from './routes/api/repl.execute'
import { Route as ApiDemoSmsAllowlistRouteImport } from './routes/api/demo.sms-allowlist'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminMessagesRoute = AppAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminExecutionsRoute = AppAdminExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const ApiSms8InboundRoute = ApiSms8InboundRouteImport.update({
  id: '/api/sms8/inbound',
  path: '/api/sms8/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReplExecuteRoute = ApiReplExecuteRouteImport.update({
  id: '/api/repl/execute',
  path: '/api/repl/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoSmsAllowlistRoute = ApiDemoSmsAllowlistRouteImport.update({
  id: '/api/demo/sms-allowlist',
  path: '/api/demo/sms-allowlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/sms-allowlist': typeof ApiDemoSmsAllowlistRoute
  '/api/repl/execute': typeof ApiReplExecuteRoute
  '/api/sms8/inbound': typeof ApiSms8InboundRoute
  '/app/admin/executions': typeof AppAdminExecutionsRoute
  '/app/admin/messages': typeof AppAdminMessagesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/sms-allowlist': typeof ApiDemoSmsAllowlistRoute
  '/api/repl/execute': typeof ApiReplExecuteRoute
  '/api/sms8/inbound': typeof ApiSms8InboundRoute
  '/app/admin/executions': typeof AppAdminExecutionsRoute
  '/app/admin/messages': typeof AppAdminMessagesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/sms-allowlist': typeof ApiDemoSmsAllowlistRoute
  '/api/repl/execute': typeof ApiReplExecuteRoute
  '/api/sms8/inbound': typeof ApiSms8InboundRoute
  '/app/admin/executions': typeof AppAdminExecutionsRoute
  '/app/admin/messages': typeof AppAdminMessagesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/app/admin'
    | '/api/auth/$'
    | '/api/demo/sms-allowlist'
    | '/api/repl/execute'
    | '/api/sms8/inbound'
    | '/app/admin/executions'
    | '/app/admin/messages'
    | '/app/admin/users'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/api/auth/$'
    | '/api/demo/sms-allowlist'
    | '/api/repl/execute'
    | '/api/sms8/inbound'
    | '/app/admin/executions'
    | '/app/admin/messages'
    | '/app/admin/users'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/app/admin'
    | '/api/auth/$'
    | '/api/demo/sms-allowlist'
    | '/api/repl/execute'
    | '/api/sms8/inbound'
    | '/app/admin/executions'
    | '/app/admin/messages'
    | '/app/admin/users'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDemoSmsAllowlistRoute: typeof ApiDemoSmsAllowlistRoute
  ApiReplExecuteRoute: typeof ApiReplExecuteRoute
  ApiSms8InboundRoute: typeof ApiSms8InboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/messages': {
      id: '/app/admin/messages'
      path: '/messages'
      fullPath: '/app/admin/messages'
      preLoaderRoute: typeof AppAdminMessagesRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/executions': {
      id: '/app/admin/executions'
      path: '/executions'
      fullPath: '/app/admin/executions'
      preLoaderRoute: typeof AppAdminExecutionsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/api/sms8/inbound': {
      id: '/api/sms8/inbound'
      path: '/api/sms8/inbound'
      fullPath: '/api/sms8/inbound'
      preLoaderRoute: typeof ApiSms8InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repl/execute': {
      id: '/api/repl/execute'
      path: '/api/repl/execute'
      fullPath: '/api/repl/execute'
      preLoaderRoute: typeof ApiReplExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/sms-allowlist': {
      id: '/api/demo/sms-allowlist'
      path: '/api/demo/sms-allowlist'
      fullPath: '/api/demo/sms-allowlist'
      preLoaderRoute: typeof ApiDemoSmsAllowlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminExecutionsRoute: typeof AppAdminExecutionsRoute
  AppAdminMessagesRoute: typeof AppAdminMessagesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminExecutionsRoute: AppAdminExecutionsRoute,
  AppAdminMessagesRoute: AppAdminMessagesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDemoSmsAllowlistRoute: ApiDemoSmsAllowlistRoute,
  ApiReplExecuteRoute: ApiReplExecuteRoute,
  ApiSms8InboundRoute: ApiSms8InboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
