/**
 * @file router.tsx
 * @description TanStack Router configuration used by TanStack Start.
 * @module routes
 */
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

/**
 * Creates the application router for each runtime request.
 * @returns Configured TanStack Router instance.
 * @remarks The route tree is generated by TanStack Start, so this file stays as
 * the stable bridge between file-based routes and the runtime router.
 */
export function getRouter(): ReturnType<typeof createRouter> {
  return createRouter({
    routeTree,
    scrollRestoration: true,
  });
}

/**
 * Router type registered with TanStack Router's module augmentation.
 * @remarks Registering this keeps route links and generated paths type-safe
 * once the route tree has been generated.
 */
declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
